<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Hina.Core\Hina.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hina.Host.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationIcon>..\img\HinaHPack_Logo.ico</ApplicationIcon>
    <PackageIcon>HinaPack_Logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\img\HinaPack_Logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
